/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Uno Vault
 */
export interface Vault {
  idCardValue: string;
  vaultSchemaMajor: number;
  uuid: string;
  email: string | null;
  validatedPhoneNumber: string | null;
  manualItems?: ManualItem[];
  vault?: {
    id: string;
    name: string;
    username?: string | null;
    password?: string | null;
    intendedPassword?: string | null;
    intendedOTPSeed?: string | null;
    otpSeed?: string | null;
    notes?: string | null;
    relatedItems?: unknown[];
    ssoProvider?: unknown[] | null;
    [k: string]: unknown;
  }[];
  privateKeys?: {
    name: string;
    key: string;
    password?: string | null;
    walletAddresses?: string[];
    notes?: string | null;
    url?: string | null;
    id: string;
    [k: string]: unknown;
  }[];
  groups?: {
    id: string;
    seed: string;
    ownerPublicSigningKey: string;
    [k: string]: unknown;
  }[];
  contacts?: unknown[];
  confidants?: unknown[];
  friends?: unknown[];
  oldPasswords?: string[];
  creditCards?: {
    id: string;
    type?: string | null;
    name?: string | null;
    holder: string;
    number: string;
    expiration: string;
    cvv?: string | null;
    addressUUID?: string | null;
    [k: string]: unknown;
  }[];
  addresses?: {
    id: string;
    line1: string;
    line2?: string | null;
    city: string;
    state: string;
    zip: string;
    country: string;
    [k: string]: unknown;
  }[];
  notes?: {
    id: string;
    title: string;
    notes: string;
    [k: string]: unknown;
  }[];
  refreshTokens?: {
    id: string;
    clientId: string;
    refreshToken: string;
    [k: string]: unknown;
  }[];
}
export interface ManualItem {
  id: string;
  name?: string | null;
  url?: string | null;
  username?: string | null;
  password?: string | null;
  intendedPassword?: string | null;
  otpSeed?: string | null;
  notes?: string | null;
  relatedItems?: unknown[];
  ssoProvider?: unknown[] | null;
  [k: string]: unknown;
}
